// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtM227kP5bDXB_3MNydEI_A-ZPBNT_4o0',
    appId: '1:292401008905:web:c7f56693347a3e9c1bc3d8',
    messagingSenderId: '292401008905',
    projectId: 'to-do-list-7264a',
    authDomain: 'to-do-list-7264a.firebaseapp.com',
    storageBucket: 'to-do-list-7264a.firebasestorage.app',
    measurementId: 'G-Z98XDD2CFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3f7-IiU3cu6SHNnQrf6jcWxiiShzSUY',
    appId: '1:292401008905:android:e378b851883ee4571bc3d8',
    messagingSenderId: '292401008905',
    projectId: 'to-do-list-7264a',
    storageBucket: 'to-do-list-7264a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkhnnLMlQZUVpV0_tJgY58i_94gu0arFI',
    appId: '1:292401008905:ios:93b540bd2a957c251bc3d8',
    messagingSenderId: '292401008905',
    projectId: 'to-do-list-7264a',
    storageBucket: 'to-do-list-7264a.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkhnnLMlQZUVpV0_tJgY58i_94gu0arFI',
    appId: '1:292401008905:ios:93b540bd2a957c251bc3d8',
    messagingSenderId: '292401008905',
    projectId: 'to-do-list-7264a',
    storageBucket: 'to-do-list-7264a.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtM227kP5bDXB_3MNydEI_A-ZPBNT_4o0',
    appId: '1:292401008905:web:13d9741334f10f531bc3d8',
    messagingSenderId: '292401008905',
    projectId: 'to-do-list-7264a',
    authDomain: 'to-do-list-7264a.firebaseapp.com',
    storageBucket: 'to-do-list-7264a.firebasestorage.app',
    measurementId: 'G-LTY8NY9341',
  );
}
